# Generated by Django 4.2.7 on 2025-10-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('stock_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('blog', 'Blog Post'), ('event', 'Event'), ('news', 'News Article'), ('research', 'Research Report'), ('announcement', 'Company Announcement')], default='news', max_length=20)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('key_points', models.JSONField(default=list)),
                ('ai_analysis', models.TextField(blank=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date', '-fetched_at'],
                'indexes': [models.Index(fields=['symbol', 'is_active'], name='api_stockin_symbol_a8d623_idx'), models.Index(fields=['symbol', 'sentiment', 'is_active'], name='api_stockin_symbol_045263_idx'), models.Index(fields=['fetched_at'], name='api_stockin_fetched_12fb1e_idx')],
                'unique_together': {('symbol', 'title', 'published_date')},
            },
        ),
    ]
