# Generated by Django 4.2.7 on 2025-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watchlist_userpreferences_watchlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedChartDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(db_index=True, help_text='Session ID for anonymous users', max_length=255)),
                ('chart_name', models.CharField(max_length=255)),
                ('series_ids', models.JSONField(help_text='List of FRED series IDs in this chart')),
                ('series_metadata', models.JSONField(default=dict, help_text='Metadata about each series (name, frequency, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('area', 'Area')], default='line', max_length=20)),
                ('show_legend', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_session', 'created_at'], name='api_savedch_user_se_7b57c8_idx')],
            },
        ),
    ]
