# Generated by Django 4.2.7 on 2025-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedchartdisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedchartdisplay',
            name='formulas',
            field=models.JSONField(blank=True, help_text="List of formulas for custom analysis (e.g., ['AAPL = price(AAPL)', 'SMA = sma(AAPL, 20)'])", null=True),
        ),
        migrations.AddField(
            model_name='savedchartdisplay',
            name='source_type',
            field=models.CharField(choices=[('fred', 'FRED Economic Data'), ('custom_analysis', 'Custom Analysis')], default='fred', help_text='Source of the chart data', max_length=20),
        ),
        migrations.AddField(
            model_name='savedchartdisplay',
            name='symbols',
            field=models.JSONField(blank=True, help_text="List of stock symbols needed for custom analysis (e.g., ['AAPL', 'MSFT'])", null=True),
        ),
        migrations.AlterField(
            model_name='savedchartdisplay',
            name='series_ids',
            field=models.JSONField(help_text='List of FRED series IDs or custom series labels'),
        ),
    ]
