# Generated by Django 4.2.7 on 2025-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_savedchartdisplay_formulas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedchartdisplay',
            name='source_type',
            field=models.CharField(choices=[('fred', 'FRED Economic Data'), ('custom_analysis', 'Custom Analysis'), ('crypto', 'Cryptocurrency')], default='fred', help_text='Source of the chart data', max_length=20),
        ),
    ]
