# Generated by Django 4.2.7 on 2025-11-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_savedchartdisplay_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin users have access to user management and system settings'),
        ),
    ]
