# Generated by Django 4.2.7 on 2025-12-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_savedchartdisplay_user_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedchartdisplay',
            new_name='api_savedch_user_id_680494_idx',
            old_name='api_savedch_user_id_8fef91_idx',
        ),
    ]
