# Generated by Django 4.2.7 on 2026-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_api_savedch_user_id_8fef91_idx_api_savedch_user_id_680494_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='agent_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PortfolioRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('stock_name', models.CharField(blank=True, max_length=255)),
                ('recommendation', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=4)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reasoning', models.JSONField(default=list)),
                ('signals', models.JSONField(default=dict)),
                ('raw_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'indexes': [models.Index(fields=['symbol', 'updated_at'], name='api_portfol_symbol_e421c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('stock_name', models.CharField(blank=True, max_length=255)),
                ('impact_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('key_developments', models.JSONField(default=list)),
                ('entities_mentioned', models.JSONField(default=list)),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'indexes': [models.Index(fields=['symbol', 'updated_at'], name='api_newssyn_symbol_eddb81_idx')],
            },
        ),
    ]
